language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("PackedMatrixMultiVectorProducts")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("PackedMatrixMultiVectorProducts")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
