name = "PackedMatrixMultiVectorProducts" 
uuid = "8090689f-6272-5167-a762-b1b7ce6fe988"
authors = ["David Gleich <dgleich@purdue.edu>","Huda Nassar <hnassar@purdue.edu>", "Yanfei Ren <ren105@purdue.edu>"]
version = "v1.0.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "Random", "LinearAlgebra", "SparseArrays"]

